/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apython_python_pythonhost_PythonExecute */

#ifndef _Included_com_apython_python_pythonhost_PythonExecute
#define _Included_com_apython_python_pythonhost_PythonExecute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apython_python_pythonhost_PythonExecute
 * Method:    nativeTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_PythonExecute_nativeTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
