/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apython_python_pythonhost_interpreter_PythonInterpreter */

#ifndef _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
#define _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    nativeGetPythonVersion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_nativeGetPythonVersion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    runInterpreter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_runInterpreter
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jobjectArray, jstring);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    interruptTerminal
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_interruptTerminal
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    openPseudoTerminal
 * Signature: (V)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_openPseudoTerminal
        (JNIEnv *, jclass);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    closePseudoTerminal
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_closePseudoTerminal
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    getPseudoTerminalPath
 * Signature: (Ljava/io/FileDescriptor;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_getPseudoTerminalPath
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    getEnqueueInput
 * Signature: (Ljava/io/FileDescriptor;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_getEnqueueInput
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif // _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
