/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apython_python_pythonhost_interpreter_PythonInterpreter */

#ifndef _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
#define _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    nativeGetPythonVersion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_nativeGetPythonVersion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    runInterpreter
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_runInterpreter
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jobjectArray, jboolean);

/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    dispatchKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_dispatchKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apython_python_pythonhost_interpreter_PythonInterpreter
 * Method:    sendStringToStdin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_sendStringToStdin
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    getEnqueueInput
 * Signature: (V)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_getEnqueueInput
        (JNIEnv *, jobject);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    interruptInterpreter
 * Signature: (V)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_interruptInterpreter
        (JNIEnv *, jobject);

/*
 * Class:     com_apython_python_pythonhost_PythonInterpreter
 * Method:    stopInterpreter
 * Signature: (V)V
 */
JNIEXPORT void JNICALL Java_com_apython_python_pythonhost_interpreter_PythonInterpreter_stopInterpreter
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif // _Included_com_apython_python_pythonhost_interpreter_PythonInterpreter
